set -g history-limit 3000
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
#set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'jimeh/tmux-themepack'
#set -g @themepack 'powerline/default/orange'
set -g @themepack 'powerline/block/blue'

set-window-option mode-keys vi
# 1. Force vi mode keys just in case
setw -g mode-keys vi
# 2. Map 'v' to begin selection (like in vim)
bind-key -T copy-mode-vi v send-keys -X begin-selection
# 3. Map 'y' to copy to the system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# set -g @continuum-boot 'on'
# set -g @continuum-restore 'on'

# # show hostname, date, time, and battery in right status bar NOT WORKING CURRENTLY
set-option -g status-right '#[fg=green]#H#[default] %m/%d/%y %I:%M\
 [fg=red]#(battery discharging)#[default]#(battery charging)'

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Sane scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Sane scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

#tmux-battery
#set -g status-right '#{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '


# Ctrl + left/right to move by whole word
set-window-option -g xterm-keys on

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
